Implement more general cv mechanism
OpenSTEF/openstef pull request #333
Opened 2022-04-01 13:18 UTC by AlexisMignon

# Implement a more general cv mechanism.

## Configuration

We add two configuration fields to `PredictionJobDataClass`:

* `train_split_func`
* `backtest_split_fun`

Using a new data class `SplitFuncDataClass` with two fields:

* `function` either a string or a function
* `arguments` additional arguments to be provided to the function.

The train function is assumed to return a triplet of data frames (train, validation, test).
The backtest function is assumed to return an iterable on such triplets

## Modifications to `train_model` pipeline.
To be the most general, we factorized `train_pipeline_common` into subparts:
* feature application
* data splitting
* model training

The default data splitting function allows using a default function used a custom split function defined in the prediction job

This allows us to use those subfunctions in the backtest pipeline, which has been deeply modified.

## Modifications to `create_forecast_backtest`

We use the new subfunctions. We do not separate the case `n_folds == 1` any more. While we usually try to keep the code unchanged when new features are added, in this case we tried to reimplement the original cv mechanism using the new one. 

Closes #295

2022-04-01 13:46 UTC, AlexisMignon commented
Note that so far, we have tested that, when no configuration is provided, the existing tests still pass.

Before considering including the PR we should

* [ ] Validate the behaviour change of the backtest pipeline (datasets with features are now returned)
* [ ] check that the implemented default cv mechanism behaves as the original one.
* [ ] Implement unittest using configurations

2022-04-13 12:21 UTC, JanMaartenvanDoorn requested changes
Nice way of making the cross validation more configurable! I have a few minor remarks about documentation and type hints, please check that alle methods have input typehints, output typehints and at least some documentation (does not have to be elaborate). Furthermore some thoughts on where to put the new back_test split function and renaming the new "pipeline_step" functions. I am curious about your thoughts.

2022-04-13 12:21 UTC, JanMaartenvanDoorn commented on openstef/pipeline/train_create_forecast_backtest.py
> -    """Pipeline for a back test.
Here you remove the documentation of the `train_model_and_forecast_back_test` , Could you please update the documentation and add it to the updated function?

2022-04-13 12:21 UTC, JanMaartenvanDoorn commented on openstef/pipeline/train_create_forecast_backtest.py
> +    pj, modelspecs, train_data, validation_data, test_data
Also here, please add some documentation (can be short) and type hints so it is clear how to use this function.

2022-04-13 12:21 UTC, JanMaartenvanDoorn commented on openstef/pipeline/train_create_forecast_backtest.py
> +    input_data, n_folds, test_fraction=0.15, stratification_min_max=True
Please add documentation and typehints.

2022-04-13 12:21 UTC, JanMaartenvanDoorn commented on openstef/pipeline/train_model.py
> +        trained_model (RegressorMixin): the trained model
Nice updated documentation!

2022-04-13 15:22 UTC, AlexisMignon commented on openstef/pipeline/train_model.py
> +    data_with_features = train_pipeline_compute_features(
So I have renamed the functions with a train_pipeline_step_* prefix.

2022-04-15 07:25 UTC, AlexisMignon commented
There are some coverage issues left which are treated in the PR linked to the `save_train_forecasts` PR.

2022-04-15 09:07 UTC, JanMaartenvanDoorn approved these changes
Good typehints and documentation!

2022-04-20 07:54 UTC, AlexisMignon commented
@JanMaartenvanDoorn. Should we merge ?

2022-04-28 08:29 UTC, JanMaartenvanDoorn commented
> @JanMaartenvanDoorn. Should we merge ?

I think this is fine, if you fix the merge conflicts you can merge it.

2022-04-28 10:39 UTC, merged